### ISSUE TITLE
Add copyright notice and contribution guidelines

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-ims#1]
Adobe open source office review was done [here](https://git.corp.adobe.com/OpenSourceAdvisoryBoard/opensource_submission_process/issues/661).

Copying over details:

- Please add a `CONTRIBUTING.md` file to the repo. There's a generic Magento template available [here](https://github.com/adobe/starter-repo/blob/master/.github/CONTRIBUTING_MAGENTO.md) that you can copy over and customize. The Adobe CLA and code of conduct language must remain, though.
- Please add a [`COPYING.txt`](https://github.com/adobe/starter-repo/blob/master/COPYING.txt) to the repo.

**Comment by sivaschenko** [comment]
Added
