### ISSUE TITLE
Missing tag 2.1.3-p5  required by magento/product-community-edition:2.4.4-p5

### ISSUE THREAD

**Issue by Vinai** [magento/adobe-ims#17]
The package `magento/product-community-edition:2.4.4-p5` requires `magento/adobe-ims:2.1.3-p5`.

The package `magento/adobe-ims:2.1.3-p5` is available on repo.magento.com, but there is no matching tag in this git repository.

Could you please add it?

### Preconditions (*)
This github repo in state it is at the time or writing.

### Steps to reproduce (*)
Try to check out the repository in the state of package `magento/adobe-ims:2.1.3-p5`.

### Expected result (*)
Being able to inspect the code for 2.1.3-p5 in the repository

### Actual result (*)
Tag 2.1.3-p5 not found.

**Comment by sidolov** [comment]
@Vinai thanks for catching this, tag is available now: https://github.com/magento/adobe-ims/releases/tag/2.1.3-p5

**Comment by Vinai** [comment]
Thank you @sidolov, that was very fast!
