### ISSUE TITLE
Image isn't displayed next to account name in the Adobe Stock

### ISSUE THREAD

**Issue by engcom-Lima** [magento/adobe-ims#4]
### Preconditions (*)

1. Magento 2.4-develop with Adobe Stock Integration - 2.0-master and IMS - 2.0-master
2. Cloud - Magento ver. 2.4.0-p1
3. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
4. Enhanced Media Gallery Enabled
5. Image added to Adobe Stock profile in the `https://account.adobe.com/`

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Click on the "Search Adobe Stock" button
3. Click "Sign in"

### Expected result (*)

Image displays next to account name in the Adobe Stock

### Actual result (*)

Image isn`t displays next to account name in the Adobe Stock
![Screenshot_91](https://user-images.githubusercontent.com/60198022/90138426-a78f6880-dd7f-11ea-8391-9118bb2df61a.png)
![Screenshot_89](https://user-images.githubusercontent.com/60198022/90138463-b7a74800-dd7f-11ea-9993-64728100896b.png)
![Screenshot_86](https://user-images.githubusercontent.com/60198022/90139997-c858bd80-dd81-11ea-92ef-481955460c9b.png)

Additional details:
Profile image url is not saved to adobe_stock_profile table in the database

Error in the exception.log  
`Notice: Undefined offset: 276 in /app/vendor/magento/module-adobe-ims/Model/GetImage.php on line 74`

**Comment by Nazar65** [comment]
@magento i'm working on it

**Comment by Nazar65** [comment]
@magento I am working on this

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Rechecked with default image and with a Custom image. The issue is not reproducible.
